version: '3.8'

services:
  app:
    # image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always  # Habilita o reinício automático
    # container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      # - ./nginx-conf_d:/etc/nginx/conf.d
      - ./nginx:/etc/nginx

  